version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      # site
      - ./web:/usr/share/nginx/html/
      # Proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      # host:container
      - 80:80
  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app # Dentro do container
    command: bash ./app.sh